config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks
  #resources :users
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/support.rb
class Support < ApplicationRecord
  validates :task, presence: true, length: {maximum: 50}
  validates :task, presence: true, length: {maximum: 100}
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true, length: {maximum: 50}
  validates :content, presence: true, length: {maximum: 100}
  belongs_to :use
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[edit update destroy ]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end
  
  def create
    @task = Task.new(task_params)
      if @task.save
        redirect_to tasks_url, notice: "Task was successfully created." 
      else
        redirect_to tasks_url, notice: "An error has occurred." 
      end
  end

  def update
    if @task.update(task_params)    
      redirect_to tasks_url, notice: "Task has been successfully updated." 
    else
      redirect_to edit_task_url,notice: "An error has occered"
    end
  end
  
  def show 
    @tasks = Task.all
  end

  def destroy
    if @task.present?
         @task.destroy
      redirect_to tasks_url, notice:  "Task has been deleted!"
    end
  end 

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:task,:content)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_task, only: %i[edit update destroy ]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end
  
  def create
    @task = Task.new(task_params)
      if @task.save
        redirect_to tasks_url, notice: "Task was successfully created." 
      else
        redirect_to tasks_url, notice: "An error has occurred." 
      end
  end

  def update
    if @task.update(task_params)    
      redirect_to tasks_url, notice: "Task has been successfully updated." 
    else
      redirect_to edit_task_url,notice: "An error has occered"
    end
  end
  
  def show 
    @tasks = Task.all
  end

  def destroy
    if @task.present?
         @task.destroy
      redirect_to tasks_url, notice:  "Task has been deleted!"
    end
  end 

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show ]
  def show
  end

  def set_user
    @user = User.find(params[:id])
  end      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/supports/_form.html.erb
<%= form_with(model: @support, local: true) do |form| %>
  <%= form.label :task %>
  <%= form.text_field :task %>
  <%= form.label :content %>
  <%= form.text_field :content %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  <%= link_to "一覧画面にもどる", supports_path%>

app/views/supports/new.html.erb
<div class = field>
  <h1>Task 作成画面</h1>
</div>
  <%= render 'form', support: @support %>

app/views/supports/show.html.erb
<table>
  <thead>
    <h3> Task一覧</h3>
      <%= link_to 'Task 新規作成', new_support_path %></button>
      <%= link_to 'Task 管理画面', supports_path %></button>
  </thead>

  <tbody>
    <% @supports.each do |p| %>
      <tr>
        <td><%= p.task %></td>
        <td><%= p.content %></td>
      <tr>
    <%end%>
  </tbody>
</table>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p id="notice"><%= notice %></p>
<h3>タスク管理支援画面</h3>
<table>
  <tbody>
    <% @tasks.each do |t| %>
      <tr>
        <td>タスク名：<%= t.title %> </td>
        <td>内容：<%= t.content %></td>
        <td><%= link_to '新規作成',new_task_path%>
        <td><%= link_to '編集',edit_task_path(task.id)%>
        <td><%= link_to '削除',task_path(task.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to ' タスク一覧画面',task_path(task.id)%>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<div class = field>
  <h1>Task 作成画面</h1>
</div>
  <%= render 'form', task: @task %>

app/views/todos/_form.html.erb
<%= form_with(model: @todo, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :content %>
  <%= form.text_field :content %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  <%= link_to "一覧画面にもどる", todos_path%>

app/views/todos/edit.html.erb
<h2>編集画面</h2>
<%= render 'form', todo: @todo %>

app/views/todos/index.html.erb
<h1>Tasks#index</h1>
<p id="notice"><%= notice %></p>
<h3>タスク管理支援画面</h3>
<table>
  <tbody>
    <% @todos.each do |t| %>
      <tr>
        <td>タスク名：<%= t.title %> </td>
        <td>内容：<%= t.content %></td>
        <td><%= link_to '新規作成',new_todo_path%>
        <td><%= link_to '編集',edit_task_path(todo.id)%>
        <td><%= link_to '削除',task_path(todo.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to ' タスク一覧画面',task_path(todo.id)%>
    <% end %>
  </tbody>
</table>

app/views/todos/new.html.erb
<div class = field>
  <h1>Task 作成画面</h1>
</div>
  <%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<table>
  <thead>
    <h3> Task一覧</h3>
      <%= link_to 'Task 新規作成', new_todo_path %></button>
      <%= link_to 'Task 管理画面', todos_path %></button>
  </thead>

  <tbody>
    <% @todos.each do |p| %>
      <tr>
        <td><%= p.title %></td>
        <td><%= p.content %></td>
      <tr>
    <%end%>
  </tbody>
</table>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
  <p>名前: <%= @user.name %></p>
  <p>メールアドレス: <%= @user.email %></p>
  <p> パスワード: <%= @user.password %></p>
    <%= link_to '一覧画面へ',tasks_path%>